apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-gce
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  gcePersistentDisk:
    pdName: mygcepd
    fsType: ext4
    